### ISSUE TITLE
remove unused css

### ISSUE THREAD

**Issue by cTxplorer** [fhrf/fhrf.github.io#3]
There is unused CSS that can be removed

All stylesheets are inside `\style` dir

**Comment by shngt** [comment]
Hi, mind if I pick this up?

**Comment by SPOCTONE** [comment]
Hello there :) so what you're basically asking here is to remove the code inserted as comments in the three css files inside the \style dir right? if what i'm saying is correct, pls assign me to this issue and i'll do it ASAP

**Comment by cTxplorer** [comment]
@shngt since you were the first to comment, assigning it to you.. Please go ahead.

@SPOCTONE there are other issues that I have opened, and even many more on the website. Please feel free to raise PR with that. I hope you understand :)

**Comment by SPOCTONE** [comment]
no problem! will look into it.

**Comment by shngt** [comment]
Hi, could you please close this @cTxplorer ?
